<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class AchievementsSeeder extends Seeder
{
    public function run(): void
    {
        $rows = [
            [
                'code' => 'milestone_common_first_steps',
                'title' => 'First Steps',
                'description' => 'Create your account.',
                'category' => 'milestone',
                'rarity' => 'common',
            ],
            [
                'code' => 'nutrition_common_first_bite',
                'title' => 'First Bite',
                'description' => 'Log your first meal.',
                'category' => 'nutrition',
                'rarity' => 'common',
            ],
            [
                'code' => 'workout_common_first_rep',
                'title' => 'First Rep',
                'description' => 'Log your first exercise.',
                'category' => 'workout',
                'rarity' => 'common',
            ],
            [
                'code' => 'milestone_common_profile_complete',
                'title' => 'Profile Complete',
                'description' => 'Fill in weight, height, goals & avatar.',
                'category' => 'milestone',
                'rarity' => 'common',
            ],
            [
                'code' => 'nutrition_common_calorie_counter',
                'title' => 'Calorie Counter',
                'description' => 'Hit your calorie target once.',
                'category' => 'nutrition',
                'rarity' => 'common',
            ],
            [
                'code' => 'workout_common_workout_complete',
                'title' => 'Workout Complete',
                'description' => 'Finish your first full workout session.',
                'category' => 'workout',
                'rarity' => 'common',
            ],
            [
                'code' => 'milestone_common_calorie_calculated',
                'title' => 'Calorie Calculated',
                'description' => 'Generate your BMR/TDEE.',
                'category' => 'milestone',
                'rarity' => 'common',
            ],
            [
                'code' => 'nutrition_common_protein_focus',
                'title' => 'Protein Focus',
                'description' => 'Reach your protein goal in a day.',
                'category' => 'nutrition',
                'rarity' => 'common',
            ],
            [
                'code' => 'workout_common_sweat_session',
                'title' => 'Sweat Session',
                'description' => 'Log 3 workouts.',
                'category' => 'workout',
                'rarity' => 'common',
            ],
            [
                'code' => 'milestone_common_macro_master_starter',
                'title' => 'Macro Master (Starter)',
                'description' => 'Set your nutrition goals.',
                'category' => 'milestone',
                'rarity' => 'common',
            ],
            [
                'code' => 'nutrition_common_hydrated',
                'title' => 'Hydrated',
                'description' => 'Log water intake',
                'category' => 'nutrition',
                'rarity' => 'common',
            ],
            [
                'code' => 'workout_common_strength_starter',
                'title' => 'Strength Starter',
                'description' => 'Increase weight in any exercise once.',
                'category' => 'workout',
                'rarity' => 'common',
            ],
            [
                'code' => 'milestone_common_week_one',
                'title' => 'Week One',
                'description' => 'Log activity for 7 days total.',
                'category' => 'milestone',
                'rarity' => 'common',
            ],
            [
                'code' => 'nutrition_common_macro_balanced',
                'title' => 'Macro Balanced',
                'description' => 'Stay within ±10% of all macros in a day.',
                'category' => 'nutrition',
                'rarity' => 'common',
            ],
            [
                'code' => 'workout_common_volume_builder',
                'title' => 'Volume Builder',
                'description' => 'Perform 20 total sets (lifetime).',
                'category' => 'workout',
                'rarity' => 'common',
            ],
            [
                'code' => 'milestone_common_data_driven',
                'title' => 'Data Driven',
                'description' => 'View your progress graph for the first time.',
                'category' => 'milestone',
                'rarity' => 'common',
            ],
            [
                'code' => 'nutrition_common_meal_prepper',
                'title' => 'Meal Prepper',
                'description' => 'Log 3 meals in one day.',
                'category' => 'nutrition',
                'rarity' => 'common',
            ],
            [
                'code' => 'workout_common_cardio_kickoff',
                'title' => 'Cardio Kickoff',
                'description' => 'Log any cardio session.',
                'category' => 'workout',
                'rarity' => 'common',
            ],
            [
                'code' => 'milestone_common_goal_setter',
                'title' => 'Goal Setter',
                'description' => 'Create your first workout plan.',
                'category' => 'milestone',
                'rarity' => 'common',
            ],
            [
                'code' => 'nutrition_common_clean_day',
                'title' => 'Clean Day',
                'description' => 'Stay under your calorie limit for a full day.',
                'category' => 'nutrition',
                'rarity' => 'common',
            ],
            [
                'code' => 'workout_common_push_day',
                'title' => 'Push Day',
                'description' => 'Complete a push workout.',
                'category' => 'workout',
                'rarity' => 'common',
            ],
            [
                'code' => 'milestone_common_routine_builder',
                'title' => 'Routine Builder',
                'description' => 'Add at least 3 exercises to a workout.',
                'category' => 'milestone',
                'rarity' => 'common',
            ],
            [
                'code' => 'nutrition_common_bulk_initiated',
                'title' => 'Bulk Initiated',
                'description' => 'Exceed calorie target intentionally (if in bulk mode).',
                'category' => 'nutrition',
                'rarity' => 'common',
            ],
            [
                'code' => 'workout_common_pull_day',
                'title' => 'Pull Day',
                'description' => 'Complete a pull workout.',
                'category' => 'workout',
                'rarity' => 'common',
            ],
            [
                'code' => 'milestone_common_consistency_begins',
                'title' => 'Consistency Begins',
                'description' => 'Log 3 workouts.',
                'category' => 'milestone',
                'rarity' => 'common',
            ],
            [
                'code' => 'nutrition_common_cut_started',
                'title' => 'Cut Started',
                'description' => 'Stay in calorie deficit for one day.',
                'category' => 'nutrition',
                'rarity' => 'common',
            ],
            [
                'code' => 'workout_common_leg_day_survivor',
                'title' => 'Leg Day Survivor',
                'description' => 'Complete a leg workout.',
                'category' => 'workout',
                'rarity' => 'common',
            ],
            [
                'code' => 'milestone_common_tracking_mode_on',
                'title' => 'Tracking Mode On',
                'description' => 'Log both workout and nutrition in the same day.',
                'category' => 'milestone',
                'rarity' => 'common',
            ],
            [
                'code' => 'nutrition_common_7_day_tracker',
                'title' => '7-Day Tracker',
                'description' => 'Log nutrition 7 days total.',
                'category' => 'nutrition',
                'rarity' => 'common',
            ],
            [
                'code' => 'workout_common_weekly_warrior',
                'title' => 'Weekly Warrior',
                'description' => 'Train 3 times in one week',
                'category' => 'workout',
                'rarity' => 'common',
            ],
            [
                'code' => 'milestone_uncommon_two_week_streak',
                'title' => 'Two Week Streak',
                'description' => 'Log activity 14 days in a row.',
                'category' => 'milestone',
                'rarity' => 'uncommon',
            ],
            [
                'code' => 'nutrition_uncommon_protein_priority',
                'title' => 'Protein Priority',
                'description' => 'Hit protein goal 7 days in a row.',
                'category' => 'nutrition',
                'rarity' => 'uncommon',
            ],
            [
                'code' => 'workout_uncommon_four_week_grind',
                'title' => 'Four Week Grind',
                'description' => 'Train 4 weeks in a row (at least 2x per week).',
                'category' => 'workout',
                'rarity' => 'uncommon',
            ],
            [
                'code' => 'milestone_uncommon_monthly_member',
                'title' => 'Monthly Member',
                'description' => 'Use the app for 30 total days.',
                'category' => 'milestone',
                'rarity' => 'uncommon',
            ],
            [
                'code' => 'nutrition_uncommon_calorie_control',
                'title' => 'Calorie Control',
                'description' => 'Stay within ±5% of calories for 5 days.',
                'category' => 'nutrition',
                'rarity' => 'uncommon',
            ],
            [
                'code' => 'workout_uncommon_volume_machine',
                'title' => 'Volume Machine',
                'description' => 'Perform 200 total sets lifetime.',
                'category' => 'workout',
                'rarity' => 'uncommon',
            ],
            [
                'code' => 'milestone_uncommon_goal_chaser',
                'title' => 'Goal Chaser',
                'description' => 'Update your goal and track progress for 14 days.',
                'category' => 'milestone',
                'rarity' => 'uncommon',
            ],
            [
                'code' => 'nutrition_uncommon_macro_mastery',
                'title' => 'Macro Mastery',
                'description' => 'Hit all macro targets 5 times.',
                'category' => 'nutrition',
                'rarity' => 'uncommon',
            ],
            [
                'code' => 'workout_uncommon_strength_improver',
                'title' => 'Strength Improver',
                'description' => 'Increase weight in 5 different exercises.',
                'category' => 'workout',
                'rarity' => 'uncommon',
            ],
            [
                'code' => 'milestone_uncommon_graph_addict',
                'title' => 'Graph Addict',
                'description' => 'View progress analytics 10 times.',
                'category' => 'milestone',
                'rarity' => 'uncommon',
            ],
            [
                'code' => 'nutrition_uncommon_7_day_discipline',
                'title' => '7-Day Discipline',
                'description' => 'Log nutrition 7 consecutive days.',
                'category' => 'nutrition',
                'rarity' => 'uncommon',
            ],
            [
                'code' => 'workout_uncommon_progress_tracker',
                'title' => 'Progress Tracker',
                'description' => 'Improve weight in same exercise 3 times.',
                'category' => 'workout',
                'rarity' => 'uncommon',
            ],
            [
                'code' => 'milestone_uncommon_workout_architect',
                'title' => 'Workout Architect',
                'description' => 'Create 3 different workout plans.',
                'category' => 'milestone',
                'rarity' => 'uncommon',
            ],
            [
                'code' => 'nutrition_uncommon_meal_planner',
                'title' => 'Meal Planner',
                'description' => 'Log 5 meals in one day.',
                'category' => 'nutrition',
                'rarity' => 'uncommon',
            ],
            [
                'code' => 'workout_uncommon_consistency_king',
                'title' => 'Consistency King',
                'description' => 'Train 12 times in one month.',
                'category' => 'workout',
                'rarity' => 'uncommon',
            ],
            [
                'code' => 'milestone_uncommon_exercise_collector',
                'title' => 'Exercise Collector',
                'description' => 'Add 15 unique exercises.',
                'category' => 'milestone',
                'rarity' => 'uncommon',
            ],
            [
                'code' => 'nutrition_uncommon_cutting_consistency',
                'title' => 'Cutting Consistency',
                'description' => 'Stay in deficit 5 days in a row.',
                'category' => 'nutrition',
                'rarity' => 'uncommon',
            ],
            [
                'code' => 'workout_uncommon_leg_day_loyalist',
                'title' => 'Leg Day Loyalist',
                'description' => 'Complete 5 leg workouts.',
                'category' => 'workout',
                'rarity' => 'uncommon',
            ],
            [
                'code' => 'milestone_uncommon_data_consistent',
                'title' => 'Data Consistent',
                'description' => 'Log workouts and nutrition 10 times in the same week.',
                'category' => 'milestone',
                'rarity' => 'uncommon',
            ],
            [
                'code' => 'nutrition_uncommon_clean_week',
                'title' => 'Clean Week',
                'description' => 'Stay under calorie limit 7 days straight.',
                'category' => 'nutrition',
                'rarity' => 'uncommon',
            ],
            [
                'code' => 'workout_uncommon_push_pull_balanced',
                'title' => 'Push Pull Balanced',
                'description' => 'Complete 5 push & 5 pull workouts.',
                'category' => 'workout',
                'rarity' => 'uncommon',
            ],
            [
                'code' => 'milestone_uncommon_plan_adjuster',
                'title' => 'Plan Adjuster',
                'description' => 'Edit and improve an existing workout plan.',
                'category' => 'milestone',
                'rarity' => 'uncommon',
            ],
            [
                'code' => 'nutrition_uncommon_balanced_builder',
                'title' => 'Balanced Builder',
                'description' => 'Hit macro split correctly for 10 days total.',
                'category' => 'nutrition',
                'rarity' => 'uncommon',
            ],
            [
                'code' => 'workout_uncommon_pr_hunter',
                'title' => 'PR Hunter',
                'description' => 'Log 5 personal records.',
                'category' => 'workout',
                'rarity' => 'uncommon',
            ],
            [
                'code' => 'milestone_uncommon_serious_tracker',
                'title' => 'Serious Tracker',
                'description' => 'Log 20 workouts total.',
                'category' => 'milestone',
                'rarity' => 'uncommon',
            ],
            [
                'code' => 'nutrition_uncommon_hydration_habit',
                'title' => 'Hydration Habit',
                'description' => 'Log water intake 14 days total (if implemented).',
                'category' => 'nutrition',
                'rarity' => 'uncommon',
            ],
            [
                'code' => 'workout_uncommon_endurance_rising',
                'title' => 'Endurance Rising',
                'description' => 'Complete 3 cardio sessions in one week.',
                'category' => 'workout',
                'rarity' => 'uncommon',
            ],
            [
                'code' => 'milestone_uncommon_dedicated_user',
                'title' => 'Dedicated User',
                'description' => 'Log activity on 20 separate days.',
                'category' => 'milestone',
                'rarity' => 'uncommon',
            ],
            [
                'code' => 'nutrition_uncommon_nutrition_veteran',
                'title' => 'Nutrition Veteran',
                'description' => 'Log 30 days of nutrition total.',
                'category' => 'nutrition',
                'rarity' => 'uncommon',
            ],
            [
                'code' => 'workout_uncommon_iron_routine',
                'title' => 'Iron Routine',
                'description' => 'Follow the same workout plan for 3 weeks.',
                'category' => 'workout',
                'rarity' => 'uncommon',
            ],
            [
                'code' => 'milestone_rare_90_day_commitment',
                'title' => '90 Day Commitment',
                'description' => 'Use the app for 90 total days.',
                'category' => 'milestone',
                'rarity' => 'rare',
            ],
            [
                'code' => 'nutrition_rare_protein_machine',
                'title' => 'Protein Machine',
                'description' => 'Hit protein goal 30 total days.',
                'category' => 'nutrition',
                'rarity' => 'rare',
            ],
            [
                'code' => 'workout_rare_iron_addict',
                'title' => 'Iron Addict',
                'description' => 'Complete 50 workouts.',
                'category' => 'workout',
                'rarity' => 'rare',
            ],
            [
                'code' => 'milestone_rare_30_day_streak',
                'title' => '30 Day Streak',
                'description' => 'Log activity 30 consecutive days.',
                'category' => 'milestone',
                'rarity' => 'rare',
            ],
            [
                'code' => 'nutrition_rare_macro_precision',
                'title' => 'Macro Precision',
                'description' => 'Stay within ±5% of all macros for 10 days straight.',
                'category' => 'nutrition',
                'rarity' => 'rare',
            ],
            [
                'code' => 'workout_rare_strength_climber',
                'title' => 'Strength Climber',
                'description' => 'Increase weight in 10 different exercises.',
                'category' => 'workout',
                'rarity' => 'rare',
            ],
            [
                'code' => 'milestone_rare_transformation_in_progress',
                'title' => 'Transformation in Progress',
                'description' => 'Track weight changes for 60 days.',
                'category' => 'milestone',
                'rarity' => 'rare',
            ],
            [
                'code' => 'nutrition_rare_deficit_discipline',
                'title' => 'Deficit Discipline',
                'description' => 'Stay in calorie deficit 14 consecutive days.',
                'category' => 'nutrition',
                'rarity' => 'rare',
            ],
            [
                'code' => 'workout_rare_progressive_overload',
                'title' => 'Progressive Overload',
                'description' => 'Improve same exercise 5 times.',
                'category' => 'workout',
                'rarity' => 'rare',
            ],
            [
                'code' => 'milestone_rare_data_driven_athlete',
                'title' => 'Data Driven Athlete',
                'description' => 'Log workouts + nutrition 50 times each.',
                'category' => 'milestone',
                'rarity' => 'rare',
            ],
            [
                'code' => 'nutrition_rare_bulk_commitment',
                'title' => 'Bulk Commitment',
                'description' => 'Stay in calorie surplus 14 consecutive days.',
                'category' => 'nutrition',
                'rarity' => 'rare',
            ],
            [
                'code' => 'workout_rare_volume_titan',
                'title' => 'Volume Titan',
                'description' => 'Perform 1,000 total sets lifetime.',
                'category' => 'workout',
                'rarity' => 'rare',
            ],
            [
                'code' => 'milestone_rare_goal_achiever',
                'title' => 'Goal Achiever',
                'description' => 'Reach a custom goal you set (weight or strength milestone).',
                'category' => 'milestone',
                'rarity' => 'rare',
            ],
            [
                'code' => 'nutrition_rare_30_day_nutrition_streak',
                'title' => '30 Day Nutrition Streak',
                'description' => 'Log food 30 days in a row.',
                'category' => 'nutrition',
                'rarity' => 'rare',
            ],
            [
                'code' => 'workout_rare_pr_hunter_elite',
                'title' => 'PR Hunter Elite',
                'description' => 'Log 15 personal records.',
                'category' => 'workout',
                'rarity' => 'rare',
            ],
            [
                'code' => 'milestone_rare_routine_master',
                'title' => 'Routine Master',
                'description' => 'Maintain the same workout split for 8 weeks.',
                'category' => 'milestone',
                'rarity' => 'rare',
            ],
            [
                'code' => 'nutrition_rare_calorie_control_expert',
                'title' => 'Calorie Control Expert',
                'description' => 'Stay within calorie range 20 days in a month.',
                'category' => 'nutrition',
                'rarity' => 'rare',
            ],
            [
                'code' => 'workout_rare_three_month_grinder',
                'title' => 'Three Month Grinder',
                'description' => 'Train consistently for 12 weeks.',
                'category' => 'workout',
                'rarity' => 'rare',
            ],
            [
                'code' => 'milestone_rare_advanced_tracker',
                'title' => 'Advanced Tracker',
                'description' => 'Log activity on 60 different days.',
                'category' => 'milestone',
                'rarity' => 'rare',
            ],
            [
                'code' => 'nutrition_rare_meal_strategist',
                'title' => 'Meal Strategist',
                'description' => 'Log 150 meals lifetime.',
                'category' => 'nutrition',
                'rarity' => 'rare',
            ],
            [
                'code' => 'workout_rare_balanced_warrior',
                'title' => 'Balanced Warrior',
                'description' => 'Complete 10 push, 10 pull, 10 leg sessions.',
                'category' => 'workout',
                'rarity' => 'rare',
            ],
            [
                'code' => 'milestone_rare_disciplined_lifestyle',
                'title' => 'Disciplined Lifestyle',
                'description' => 'Log both nutrition & workouts 30 times in the same day.',
                'category' => 'milestone',
                'rarity' => 'rare',
            ],
            [
                'code' => 'nutrition_rare_macro_consistency',
                'title' => 'Macro Consistency',
                'description' => 'Hit all macro goals 25 total days.',
                'category' => 'nutrition',
                'rarity' => 'rare',
            ],
            [
                'code' => 'workout_rare_cardio_consistent',
                'title' => 'Cardio Consistent',
                'description' => 'Log 15 cardio sessions.',
                'category' => 'workout',
                'rarity' => 'rare',
            ],
            [
                'code' => 'milestone_rare_macro_strategist',
                'title' => 'Macro Strategist',
                'description' => 'Adjust calorie/macros and stick to them 30 days.',
                'category' => 'milestone',
                'rarity' => 'rare',
            ],
            [
                'code' => 'nutrition_rare_clean_month',
                'title' => 'Clean Month',
                'description' => 'Stay within targets for 30 total days.',
                'category' => 'nutrition',
                'rarity' => 'rare',
            ],
            [
                'code' => 'workout_rare_unbreakable_routine',
                'title' => 'Unbreakable Routine',
                'description' => 'Train at least 3x/week for 8 weeks straight.',
                'category' => 'workout',
                'rarity' => 'rare',
            ],
            [
                'code' => 'milestone_rare_progress_veteran',
                'title' => 'Progress Veteran',
                'description' => 'View progress graphs 50 times',
                'category' => 'milestone',
                'rarity' => 'rare',
            ],
            [
                'code' => 'nutrition_rare_fueling_like_a_pro',
                'title' => 'Fueling Like a Pro',
                'description' => 'Log nutrition 90 total days',
                'category' => 'nutrition',
                'rarity' => 'rare',
            ],
            [
                'code' => 'workout_rare_strength_milestone',
                'title' => 'Strength Milestone',
                'description' => 'Lift 100kg+ in any compound movement.',
                'category' => 'workout',
                'rarity' => 'rare',
            ],
            [
                'code' => 'milestone_epic_half_year_discipline',
                'title' => 'Half-Year Discipline',
                'description' => 'Use the app for 180 total days.',
                'category' => 'milestone',
                'rarity' => 'epic',
            ],
            [
                'code' => 'nutrition_epic_90_day_nutrition_streak',
                'title' => '90 Day Nutrition Streak',
                'description' => 'Log nutrition 90 days in a row.',
                'category' => 'nutrition',
                'rarity' => 'epic',
            ],
            [
                'code' => 'workout_epic_100_workout_milestone',
                'title' => '100 Workout Milestone',
                'description' => 'Complete 100 workouts.',
                'category' => 'workout',
                'rarity' => 'epic',
            ],
            [
                'code' => 'milestone_epic_60_day_streak',
                'title' => '60 Day Streak',
                'description' => 'Log activity 60 consecutive days.',
                'category' => 'milestone',
                'rarity' => 'epic',
            ],
            [
                'code' => 'nutrition_epic_macro_precision_elite',
                'title' => 'Macro Precision Elite',
                'description' => 'Hit all macro targets 45 total days.',
                'category' => 'nutrition',
                'rarity' => 'epic',
            ],
            [
                'code' => 'workout_epic_strength_ascension',
                'title' => 'Strength Ascension',
                'description' => 'Increase weight in 20 different exercises.',
                'category' => 'workout',
                'rarity' => 'epic',
            ],
            [
                'code' => 'milestone_epic_transformation_mode',
                'title' => 'Transformation Mode',
                'description' => 'Track weight consistently for 6 months.',
                'category' => 'milestone',
                'rarity' => 'epic',
            ],
            [
                'code' => 'nutrition_epic_calorie_commander',
                'title' => 'Calorie Commander',
                'description' => 'Stay within ±5% of calories for 30 days straight.',
                'category' => 'nutrition',
                'rarity' => 'epic',
            ],
            [
                'code' => 'workout_epic_progressive_overload_master',
                'title' => 'Progressive Overload Master',
                'description' => 'Improve same exercise 10 times.',
                'category' => 'workout',
                'rarity' => 'epic',
            ],
            [
                'code' => 'milestone_epic_lifestyle_locked_in',
                'title' => 'Lifestyle Locked In',
                'description' => 'Log workouts & nutrition 100 times each.',
                'category' => 'milestone',
                'rarity' => 'epic',
            ],
            [
                'code' => 'nutrition_epic_deficit_dominator',
                'title' => 'Deficit Dominator',
                'description' => 'Stay in a controlled deficit for 30 consecutive days.',
                'category' => 'nutrition',
                'rarity' => 'epic',
            ],
            [
                'code' => 'workout_epic_volume_monster',
                'title' => 'Volume Monster',
                'description' => 'Perform 3,000 total sets lifetime.',
                'category' => 'workout',
                'rarity' => 'epic',
            ],
            [
                'code' => 'milestone_epic_goal_crusher',
                'title' => 'Goal Crusher',
                'description' => 'Successfully complete 3 different goals.',
                'category' => 'milestone',
                'rarity' => 'epic',
            ],
            [
                'code' => 'nutrition_epic_bulk_strategist',
                'title' => 'Bulk Strategist',
                'description' => 'Maintain surplus correctly for 30 consecutive days.',
                'category' => 'nutrition',
                'rarity' => 'epic',
            ],
            [
                'code' => 'workout_epic_elite_pr_hunter',
                'title' => 'Elite PR Hunter',
                'description' => 'Log 30 personal records.',
                'category' => 'workout',
                'rarity' => 'epic',
            ],
            [
                'code' => 'milestone_epic_routine_architect',
                'title' => 'Routine Architect',
                'description' => 'Create and follow 5 structured workout plans.',
                'category' => 'milestone',
                'rarity' => 'epic',
            ],
            [
                'code' => 'nutrition_epic_fueling_mastery',
                'title' => 'Fueling Mastery',
                'description' => 'Log 300 meals lifetime.',
                'category' => 'nutrition',
                'rarity' => 'epic',
            ],
            [
                'code' => 'workout_epic_six_month_grinder',
                'title' => 'Six Month Grinder',
                'description' => 'Train consistently 3x/week for 6 months.',
                'category' => 'workout',
                'rarity' => 'epic',
            ],
            [
                'code' => 'milestone_epic_macro_evolution',
                'title' => 'Macro Evolution',
                'description' => 'Successfully complete both a cut and a bulk phase.',
                'category' => 'milestone',
                'rarity' => 'epic',
            ],
            [
                'code' => 'nutrition_epic_macro_discipline',
                'title' => 'Macro Discipline',
                'description' => 'Stay within macro targets 60 total days.',
                'category' => 'nutrition',
                'rarity' => 'epic',
            ],
            [
                'code' => 'workout_epic_compound_commander',
                'title' => 'Compound Commander',
                'description' => 'Hit major strength benchmark in squat, bench & deadlift (user-adjusted).',
                'category' => 'workout',
                'rarity' => 'epic',
            ],
            [
                'code' => 'milestone_epic_data_obsession',
                'title' => 'Data Obsession',
                'description' => 'Log activity on 120 different days.',
                'category' => 'milestone',
                'rarity' => 'epic',
            ],
            [
                'code' => 'nutrition_epic_clean_quarter',
                'title' => 'Clean Quarter',
                'description' => 'Maintain targets for 90 total days total.',
                'category' => 'nutrition',
                'rarity' => 'epic',
            ],
            [
                'code' => 'workout_epic_cardio_engine',
                'title' => 'Cardio Engine',
                'description' => 'Log 40 cardio sessions.',
                'category' => 'workout',
                'rarity' => 'epic',
            ],
            [
                'code' => 'milestone_epic_progress_scientist',
                'title' => 'Progress Scientist',
                'description' => 'Review progress graphs 100 times.',
                'category' => 'milestone',
                'rarity' => 'epic',
            ],
            [
                'code' => 'nutrition_epic_adaptive_nutritionist',
                'title' => 'Adaptive Nutritionist',
                'description' => 'Adjust macros based on progress 3 times and succeed.',
                'category' => 'nutrition',
                'rarity' => 'epic',
            ],
            [
                'code' => 'workout_epic_iron_consistency',
                'title' => 'Iron Consistency',
                'description' => 'Train at least 4x/week for 12 consecutive weeks.',
                'category' => 'workout',
                'rarity' => 'epic',
            ],
            [
                'code' => 'milestone_epic_fitness_identity',
                'title' => 'Fitness Identity',
                'description' => 'Maintain active tracking across 6 different months.',
                'category' => 'milestone',
                'rarity' => 'epic',
            ],
            [
                'code' => 'nutrition_epic_body_recomposition',
                'title' => 'Body Recomposition',
                'description' => 'Successfully lose fat AND gain strength simultaneously',
                'category' => 'nutrition',
                'rarity' => 'epic',
            ],
            [
                'code' => 'workout_epic_strength_transformation',
                'title' => 'Strength Transformation',
                'description' => 'Increase total lifted weight (volume) by 50% compared to first month.',
                'category' => 'workout',
                'rarity' => 'epic',
            ],
            [
                'code' => 'milestone_legendary_one_year_unbroken',
                'title' => 'One Year Unbroken',
                'description' => 'Use the app for 365 total days.',
                'category' => 'milestone',
                'rarity' => 'legendary',
            ],
            [
                'code' => 'nutrition_legendary_180_day_nutrition_streak',
                'title' => '180 Day Nutrition Streak',
                'description' => 'Log nutrition 180 consecutive days.',
                'category' => 'nutrition',
                'rarity' => 'legendary',
            ],
            [
                'code' => 'workout_legendary_200_workout_milestone',
                'title' => '200 Workout Milestone',
                'description' => 'Complete 200 workouts.',
                'category' => 'workout',
                'rarity' => 'legendary',
            ],
            [
                'code' => 'milestone_legendary_100_day_streak',
                'title' => '100 Day Streak',
                'description' => 'Log activity 100 consecutive days.',
                'category' => 'milestone',
                'rarity' => 'legendary',
            ],
            [
                'code' => 'nutrition_legendary_macro_perfectionist',
                'title' => 'Macro Perfectionist',
                'description' => 'Hit all macro targets 100 total days.',
                'category' => 'nutrition',
                'rarity' => 'legendary',
            ],
            [
                'code' => 'workout_legendary_iron_veteran',
                'title' => 'Iron Veteran',
                'description' => 'Train consistently for 12 straight months.',
                'category' => 'workout',
                'rarity' => 'legendary',
            ],
            [
                'code' => 'milestone_legendary_lifestyle_transformation',
                'title' => 'Lifestyle Transformation',
                'description' => 'Track workouts & nutrition for 12 consecutive months.',
                'category' => 'milestone',
                'rarity' => 'legendary',
            ],
            [
                'code' => 'nutrition_legendary_year_of_control',
                'title' => 'Year of Control',
                'description' => 'Stay within calorie target 200 total days.',
                'category' => 'nutrition',
                'rarity' => 'legendary',
            ],
            [
                'code' => 'workout_legendary_progressive_overload_elite',
                'title' => 'Progressive Overload Elite',
                'description' => 'Improve same exercise 20 times.',
                'category' => 'workout',
                'rarity' => 'legendary',
            ],
            [
                'code' => 'milestone_legendary_identity_shift',
                'title' => 'Identity Shift',
                'description' => 'Log activity on 250+ different days.',
                'category' => 'milestone',
                'rarity' => 'legendary',
            ],
            [
                'code' => 'nutrition_legendary_deficit_legend',
                'title' => 'Deficit Legend',
                'description' => 'Complete a 12-week disciplined fat-loss phase successfully.',
                'category' => 'nutrition',
                'rarity' => 'legendary',
            ],
            [
                'code' => 'workout_legendary_volume_god',
                'title' => 'Volume God',
                'description' => 'Perform 10,000 total sets lifetime.',
                'category' => 'workout',
                'rarity' => 'legendary',
            ],
            [
                'code' => 'milestone_legendary_goal_conqueror',
                'title' => 'Goal Conqueror',
                'description' => 'Complete 5 major personal goals.',
                'category' => 'milestone',
                'rarity' => 'legendary',
            ],
            [
                'code' => 'nutrition_legendary_lean_bulk_architect',
                'title' => 'Lean Bulk Architect',
                'description' => 'Complete a 16-week structured bulk successfully.',
                'category' => 'nutrition',
                'rarity' => 'legendary',
            ],
            [
                'code' => 'workout_legendary_pr_collector',
                'title' => 'PR Collector',
                'description' => 'Log 75 personal records.',
                'category' => 'workout',
                'rarity' => 'legendary',
            ],
            [
                'code' => 'milestone_legendary_master_of_data',
                'title' => 'Master of Data',
                'description' => 'Log workouts & nutrition 200 times each.',
                'category' => 'milestone',
                'rarity' => 'legendary',
            ],
            [
                'code' => 'nutrition_legendary_fueling_elite',
                'title' => 'Fueling Elite',
                'description' => 'Log 600 meals lifetime.',
                'category' => 'nutrition',
                'rarity' => 'legendary',
            ],
            [
                'code' => 'workout_legendary_strength_trinity',
                'title' => 'Strength Trinity',
                'description' => 'Reach elite benchmark in squat, bench & deadlift (relative to bodyweight).',
                'category' => 'workout',
                'rarity' => 'legendary',
            ],
            [
                'code' => 'milestone_legendary_disciplined_beyond_motivation',
                'title' => 'Disciplined Beyond Motivation',
                'description' => 'Train 3x/week for an entire year.',
                'category' => 'milestone',
                'rarity' => 'legendary',
            ],
            [
                'code' => 'nutrition_legendary_metabolic_master',
                'title' => 'Metabolic Master',
                'description' => 'Adjust macros 5+ times based on progress & maintain success.',
                'category' => 'nutrition',
                'rarity' => 'legendary',
            ],
            [
                'code' => 'workout_legendary_unbreakable_routine',
                'title' => 'Unbreakable Routine',
                'description' => 'Train 4x/week for 6 consecutive months.',
                'category' => 'workout',
                'rarity' => 'legendary',
            ],
            [
                'code' => 'milestone_legendary_evolution_complete',
                'title' => 'Evolution Complete',
                'description' => 'Successfully complete cut → maintenance → bulk cycles.',
                'category' => 'milestone',
                'rarity' => 'legendary',
            ],
            [
                'code' => 'nutrition_legendary_precision_quarter',
                'title' => 'Precision Quarter',
                'description' => 'Stay within ±5% calories for 60 consecutive days.',
                'category' => 'nutrition',
                'rarity' => 'legendary',
            ],
            [
                'code' => 'workout_legendary_total_volume_titan',
                'title' => 'Total Volume Titan',
                'description' => 'Double total lifted volume compared to first tracked month.',
                'category' => 'workout',
                'rarity' => 'legendary',
            ],
            [
                'code' => 'milestone_legendary_progress_historian',
                'title' => 'Progress Historian',
                'description' => 'Maintain bodyweight tracking for 12 months straight.',
                'category' => 'milestone',
                'rarity' => 'legendary',
            ],
            [
                'code' => 'nutrition_legendary_body_composition_mastery',
                'title' => 'Body Composition Mastery',
                'description' => 'Achieve major weight milestone (custom % change).',
                'category' => 'nutrition',
                'rarity' => 'legendary',
            ],
            [
                'code' => 'workout_legendary_endurance_beast',
                'title' => 'Endurance Beast',
                'description' => 'Log 100 cardio sessions.',
                'category' => 'workout',
                'rarity' => 'legendary',
            ],
            [
                'code' => 'milestone_legendary_gymtracker_veteran',
                'title' => 'GymTracker Veteran',
                'description' => 'Unlock 75% of all achievements.',
                'category' => 'milestone',
                'rarity' => 'legendary',
            ],
            [
                'code' => 'nutrition_legendary_nutrition_identity',
                'title' => 'Nutrition Identity',
                'description' => 'Log nutrition across 12 separate months.',
                'category' => 'nutrition',
                'rarity' => 'legendary',
            ],
            [
                'code' => 'workout_legendary_elite_status',
                'title' => 'Elite Status',
                'description' => 'Reach top 5% activity percentile among users (if leaderboard exists).',
                'category' => 'workout',
                'rarity' => 'legendary',
            ],
        ];

        // Upsert by code (safe to re-run)
        foreach ($rows as $r) {
            DB::table('achievements')->updateOrInsert(
                ['code' => $r['code']],
                [
                    'title' => $r['title'],
                    'description' => $r['description'],
                    'category' => $r['category'],
                    'rarity' => $r['rarity'],
                    'points' => $r['points'] ?? 0,
                    'is_active' => $r['is_active'] ?? 1,
                    'criteria' => $r['criteria'] ?? null,
                    'updated_at' => now(),
                    'created_at' => now(),
                ]
            );
        }
    }
}
